# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Allan Nordhøy <epost@anotheragency.no>, 2017
msgid ""
msgstr ""
"Project-Id-Version: fwbackups\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-01-07 01:37-0800\n"
"PO-Revision-Date: 2017-09-23 13:59+0000\n"
"Last-Translator: Allan Nordhøy <epost@anotheragency.no>\n"
"Language-Team: Norwegian Bokmål (Norway) (http://www.transifex.com/Magic/"
"fwbackups/language/nb_NO/)\n"
"Language: nb_NO\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: data/com.diffingo.fwbackups.desktop.in:3 fwbackups/ui/gtk/main.ui:22
#: fwbackups/ui/__init__.py:71
msgid "fwbackups"
msgstr "fwbackups"

#: data/com.diffingo.fwbackups.desktop.in:4
msgid "Backup or restore your files"
msgstr ""

#: data/com.diffingo.fwbackups.desktop.in:6
msgid "backup;archive;archiving;"
msgstr ""

#: data/com.diffingo.fwbackups.appdata.xml.in:7 fwbackups/ui/__init__.py:848
msgid "A feature-rich user backup program"
msgstr ""

#: fwbackups/ui/gtk/BugReport.ui:69
msgid "<span size=\"larger\" weight=\"bold\">Sorry!</span>"
msgstr "<span size=\"larger\" weight=\"bold\">Beklager!</span>"

#: fwbackups/ui/gtk/BugReport.ui:81
msgid ""
"fwbackups has run into an unexpected error. You may continue using the "
"program, however it is recommended you quit and open fwbackups again."
msgstr ""

#: fwbackups/ui/gtk/BugReport.ui:117
msgid "_Details"
msgstr "_Detaljer"

#: fwbackups/ui/gtk/backupset.ui:11
msgid "Configure Set"
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:174
msgid "Paths"
msgstr "Stier"

#: fwbackups/ui/gtk/backupset.ui:203
msgid "Destination Type:"
msgstr "Måltype:"

#: fwbackups/ui/gtk/backupset.ui:267 fwbackups/ui/gtk/backupset.ui:326
#: fwbackups/ui/gtk/main.ui:600 fwbackups/ui/gtk/main.ui:685
#: fwbackups/ui/gtk/restore.ui:202
msgid "Folder:"
msgstr "Mappe:"

#: fwbackups/ui/gtk/backupset.ui:294 fwbackups/ui/gtk/main.ui:628
msgid "/folder"
msgstr "/mappe"

#: fwbackups/ui/gtk/backupset.ui:337 fwbackups/ui/gtk/main.ui:649
#: fwbackups/ui/gtk/restore.ui:275
msgid "Host:"
msgstr "Vert:"

#: fwbackups/ui/gtk/backupset.ui:349 fwbackups/ui/gtk/main.ui:661
#: fwbackups/ui/gtk/restore.ui:287
msgid "Username:"
msgstr "Brukernavn:"

#: fwbackups/ui/gtk/backupset.ui:361 fwbackups/ui/gtk/main.ui:673
#: fwbackups/ui/gtk/restore.ui:299
msgid "Password:"
msgstr "Passord:"

#: fwbackups/ui/gtk/backupset.ui:378 fwbackups/ui/gtk/main.ui:701
msgid "_Test Settings"
msgstr "_Test innstillinger"

#: fwbackups/ui/gtk/backupset.ui:401 fwbackups/ui/gtk/main.ui:725
#: fwbackups/ui/gtk/restore.ui:364
msgid "Hide password"
msgstr "Skjul passord"

#: fwbackups/ui/gtk/backupset.ui:449 fwbackups/ui/gtk/main.ui:783
#: fwbackups/ui/gtk/restore.ui:400
msgid "Port:"
msgstr "Port:"

#: fwbackups/ui/gtk/backupset.ui:500
msgid "Destination"
msgstr "Mål"

#: fwbackups/ui/gtk/backupset.ui:527
msgid ""
"Use the same syntax a crontab does to enter your settings. To obtain "
"examples and more information on crontab syntax, click 'Help'."
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:620
msgid ""
"No field verification is performed on a manual field to test if the input is "
"valid. Please make sure there are no errors."
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:687
msgid "Manual Configuration"
msgstr "Manuelt oppsett"

#: fwbackups/ui/gtk/backupset.ui:718
msgid "All Months"
msgstr "Alle måneder"

#: fwbackups/ui/gtk/backupset.ui:730
msgid "Only during:"
msgstr "Bare i løpet av:"

#: fwbackups/ui/gtk/backupset.ui:741 fwbackups/ui/gtk/backupset.ui:901
msgid "From:"
msgstr "Fra:"

#: fwbackups/ui/gtk/backupset.ui:806 fwbackups/ui/gtk/backupset.ui:958
msgid "To:"
msgstr "Til:"

#: fwbackups/ui/gtk/backupset.ui:851
msgid "<b>Months</b>"
msgstr "<b>Måneder</b>"

#: fwbackups/ui/gtk/backupset.ui:877
msgid "Only on:"
msgstr "Bare på:"

#: fwbackups/ui/gtk/backupset.ui:889
msgid "All days of the week"
msgstr "Alle dager i uken"

#: fwbackups/ui/gtk/backupset.ui:998
msgid "<b>Days of the week</b>"
msgstr "<b>Dager i uken</b>"

#: fwbackups/ui/gtk/backupset.ui:1024
msgid "At:"
msgstr "Tidspunkt:"

#: fwbackups/ui/gtk/backupset.ui:1035
msgid "All Hours"
msgstr "Alle timer"

#: fwbackups/ui/gtk/backupset.ui:1087
msgid "<b>Hours</b>"
msgstr "<b>Timer</b>"

#: fwbackups/ui/gtk/backupset.ui:1111
msgid "Only at:"
msgstr "Bare:"

#: fwbackups/ui/gtk/backupset.ui:1122
msgid "All Minutes"
msgstr "Alle minutter"

#: fwbackups/ui/gtk/backupset.ui:1153
msgid "<b>Minute</b>"
msgstr "<b>Minutt</b>"

#: fwbackups/ui/gtk/backupset.ui:1171
msgid "Easy Configuration"
msgstr "Enkelt oppsett"

#: fwbackups/ui/gtk/backupset.ui:1185
msgid ""
"Your backup will run whenever <b>all</b> of the criteria below match the "
"system time and date."
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:1210
msgid "Times"
msgstr "Tider"

#: fwbackups/ui/gtk/backupset.ui:1236 fwbackups/ui/gtk/main.ui:856
msgid "Archive (files and folders are packed into a tar archive)"
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:1250 fwbackups/ui/gtk/main.ui:870
msgid "Direct copy of the files and folders"
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:1276 fwbackups/ui/gtk/main.ui:888
msgid "Compress archive using"
msgstr "Komprimer arkiv ved bruk av"

#: fwbackups/ui/gtk/backupset.ui:1303
msgid "Backups are incremental"
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:1320 fwbackups/ui/gtk/main.ui:913
msgid "<b>Backup Format</b>"
msgstr "<b>Sikkerhetskopieringsformat</b>"

#: fwbackups/ui/gtk/backupset.ui:1339
msgid "Set is enabled"
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:1351
msgid "Include subfolders"
msgstr "Inkluder undermapper"

#: fwbackups/ui/gtk/backupset.ui:1364 fwbackups/ui/gtk/main.ui:971
msgid "Print disk geometry information to a file"
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:1377 fwbackups/ui/gtk/main.ui:958
msgid "Print installed packages to a text file"
msgstr "Skriv en liste over installerte pakker til ei tekstfil"

#: fwbackups/ui/gtk/backupset.ui:1389 fwbackups/ui/gtk/main.ui:983
msgid "Include hidden files"
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:1401 fwbackups/ui/gtk/main.ui:995
msgid "Handle sparse files efficiently"
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:1412 fwbackups/ui/gtk/main.ui:1006
msgid "Follow links"
msgstr "Følg lenker"

#: fwbackups/ui/gtk/backupset.ui:1425 fwbackups/ui/gtk/backupset.ui:1485
#: fwbackups/ui/gtk/main.ui:1019
msgid "<b>Backup Options</b>"
msgstr "<b>Valg for sikkerhetskopi</b>"

#: fwbackups/ui/gtk/backupset.ui:1442
msgid "Number of old backups to keep:"
msgstr "Antall gamle sikkerhetskopier å beholde:"

#: fwbackups/ui/gtk/backupset.ui:1471
msgid ""
"A value of  '0' makes a new backup always replace an older one. This option "
"is unavailable with incremental backups."
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:1507
msgid "Options (Simple)"
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:1557
msgid "Command to run before backup:"
msgstr "Kommando å kjøre før sikkerhetskopi:"

#: fwbackups/ui/gtk/backupset.ui:1568
msgid "Command to run after backup:"
msgstr "Kommando å kjøre etter sikkerhetskopi:"

#: fwbackups/ui/gtk/backupset.ui:1579 fwbackups/ui/gtk/main.ui:1083
msgid "Nice value of backup process:"
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:1590
msgid ""
"Exclude from backup:\n"
" (newline separated)"
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:1636
msgid ""
"The following tokens may be used in the commands:\n"
"[destination], [set], [date], [backup], [remote_host], [remote_port], "
"[remote_username], [remote_password]\n"
"\n"
"For a description of each, see the user manual."
msgstr ""

#: fwbackups/ui/gtk/backupset.ui:1666
msgid "Options (Advanced)"
msgstr "Valg (Avansert)"

#: fwbackups/ui/gtk/backupset.ui:1695
msgid "<b>Name:</b>"
msgstr "<b>Navn:</b>"

#: fwbackups/ui/gtk/confirm_dia.ui:36 fwbackups/ui/gtk/error_dia.ui:36
#: fwbackups/ui/gtk/info_dia.ui:35 fwbackups/ui/gtk/warning_dia.ui:39
msgid ""
"<span size=\"larger\" weight=\"bold\">Primary text</span>\n"
"\n"
"Secondary text"
msgstr ""

#: fwbackups/ui/gtk/confirm_dia.ui:49 fwbackups/ui/gtk/info_dia.ui:47
#: fwbackups/ui/gtk/warning_dia.ui:52
msgid "Don't show me this message again"
msgstr "Ikke vis denne meldingen igjen"

#: fwbackups/ui/gtk/export_dia.ui:10 fwbackups/ui/__init__.py:692
msgid "Export Sets"
msgstr ""

#: fwbackups/ui/gtk/export_dia.ui:44
msgid "<span size=\"larger\" weight=\"bold\">Export Sets</span>"
msgstr ""

#: fwbackups/ui/gtk/export_dia.ui:57
msgid "Select the set you would like to export."
msgstr ""

#: fwbackups/ui/gtk/export_dia.ui:96
msgid "_Export"
msgstr "_Eksporter"

#: fwbackups/ui/gtk/main.ui:63
msgid "To start, click one of the buttons on the above or use the menus."
msgstr ""

#: fwbackups/ui/gtk/main.ui:74
msgid ""
"Please do not forget to check your fwbackups log regularly to be informed "
"about any errors and/or failed backup runs."
msgstr ""

#: fwbackups/ui/gtk/main.ui:88
msgid "<b>Welcome</b>"
msgstr "<b>Velkommen</b>"

#: fwbackups/ui/gtk/main.ui:113 fwbackups/ui/gtk/main.ui:124
msgid "<i>Not Loaded</i>"
msgstr ""

#: fwbackups/ui/gtk/main.ui:136
msgid "Total backup sets:"
msgstr ""

#: fwbackups/ui/gtk/main.ui:147
msgid "Failed backup runs:"
msgstr ""

#: fwbackups/ui/gtk/main.ui:162
msgid "<b>Status</b>"
msgstr ""

#: fwbackups/ui/gtk/main.ui:181
msgid "Overview"
msgstr "Oversikt"

#: fwbackups/ui/gtk/main.ui:376 fwbackups/ui/gtk/main.ui:1119
#: fwbackups/ui/gtk/restore.ui:581
msgid "Status:"
msgstr "Status:"

#: fwbackups/ui/gtk/main.ui:386 fwbackups/ui/gtk/main.ui:1130
msgid "Backup progress:"
msgstr "Framdrift for sikkerhetskopiering:"

#: fwbackups/ui/gtk/main.ui:400
#, fuzzy
msgid "Backups Sets"
msgstr "Framdrift for sikkerhetskopiering:"

#: fwbackups/ui/gtk/main.ui:820
msgid "Destination type:"
msgstr "Måltype:"

#: fwbackups/ui/gtk/main.ui:932
msgid "Enabled"
msgstr "Påskrudd"

#: fwbackups/ui/gtk/main.ui:945
msgid "Recursive"
msgstr "Rekursivt"

#: fwbackups/ui/gtk/main.ui:1071
msgid "Exclude from backup (newline separated):"
msgstr ""

#: fwbackups/ui/gtk/main.ui:1095
msgid "<b>Advanced Options</b>"
msgstr "<b>Avanserte valg</b>"

#: fwbackups/ui/gtk/main.ui:1170 fwbackups/ui/gtk/restore.ui:592
msgid "%s"
msgstr "%s"

#: fwbackups/ui/gtk/main.ui:1266
msgid "One-Time Backup"
msgstr ""

#: fwbackups/ui/gtk/main.ui:1342
msgid "_Save to File"
msgstr "_Lagre til fil"

#: fwbackups/ui/gtk/main.ui:1390
msgid "Log Viewer"
msgstr ""

#: fwbackups/ui/gtk/main.ui:1524
msgid "Restore"
msgstr "Gjenopprett"

#: fwbackups/ui/gtk/preferences.ui:29
#, fuzzy
msgid "Enable debug log messages"
msgstr "Tidligere loggmeldinger"

#: fwbackups/ui/gtk/preferences.ui:75
#, fuzzy
msgid "Override temporary directory:"
msgstr "Tilpass midlertidig mappe"

#: fwbackups/ui/gtk/preferences.ui:94
#, fuzzy
msgid "Enable notifications"
msgstr "Vis _merknader"

#: fwbackups/ui/gtk/preferences.ui:107
#, fuzzy
msgid "<b>Options</b>"
msgstr "<b>Valg for systemkurv</b>"

#: fwbackups/ui/gtk/preferences.ui:141
msgid "Click to reset \"Don't show me again\" messages"
msgstr ""

#: fwbackups/ui/gtk/preferences.ui:174
msgid "Preferences"
msgstr "Innstillinger"

#: fwbackups/ui/gtk/restore.ui:63
msgid "Set:"
msgstr ""

#: fwbackups/ui/gtk/restore.ui:73
msgid "Date:"
msgstr "Dato:"

#: fwbackups/ui/gtk/restore.ui:147
msgid "Archive:"
msgstr "Arkiv:"

#: fwbackups/ui/gtk/restore.ui:242
msgid "/"
msgstr "/"

#: fwbackups/ui/gtk/restore.ui:311
msgid "Location:"
msgstr "Plassering:"

#: fwbackups/ui/gtk/restore.ui:326
msgid "Test Settings"
msgstr ""

#: fwbackups/ui/gtk/restore.ui:349
msgid ""
"Note: fwbackups will copy the remote backup to the disk first, then unpack "
"it. Please ensure enough disk space is available."
msgstr ""

#: fwbackups/ui/gtk/restore.ui:449
msgid "Source type:"
msgstr "Kildetype:"

#: fwbackups/ui/gtk/restore.ui:461
msgid "Restore to:"
msgstr "Gjenopprett til:"

#: fwbackups/ui/gtk/restore.ui:514
msgid ""
"Tip: entering '/' or selecting 'File System' will restore files to their "
"original locations."
msgstr ""

#: fwbackups/ui/gtk/restore.ui:540
msgid "Restore Progress:"
msgstr "Fremdrift for gjenoppretting:"

#: fwbackups/ui/gtk/restore.ui:658
msgid "_Finish"
msgstr "_Fullfør"

#: fwbackups/ui/gtk/restore.ui:671
msgid "Restore Files"
msgstr "Gjenopprett filer"

#: fwbackups/config.py:58
#, python-format
msgid "Could not create configuration folder `%s':"
msgstr "Kunne ikke opprette oppsettsmappe `%s':"

#: fwbackups/config.py:65
#, python-format
msgid "You do not have read and write permissions on folder `%s'."
msgstr "Du har ikke lese og skriverettigheter til mappa `%s'."

#: fwbackups/config.py:125
#, python-format
msgid "Key %s of is not a dictionary of options"
msgstr ""

#: fwbackups/config.py:341
#, python-format
msgid "Set '%s' failed to pass section validation"
msgstr ""

#: fwbackups/config.py:344
#, python-format
msgid "'%(a)s' is not a set configuration file."
msgstr ""

#: fwbackups/config.py:348
#, python-format
msgid ""
"Configuration section 'General' in the set configuration '%s' failed to "
"validate"
msgstr ""

#: fwbackups/config.py:351
#, python-format
msgid ""
"Configuration section 'Times' in the set configuration '%s' failed to "
"validate"
msgstr ""

#: fwbackups/config.py:364
#, python-format
msgid "Unknown option key '%(a)s' present in set configuration '%(b)s'"
msgstr ""

#: fwbackups/config.py:369
#, python-format
msgid ""
"Configuration section 'Options' in set configuration '%(a)s' failed to "
"validate: Missing options '%(b)s'"
msgstr ""

#: fwbackups/config.py:504
msgid "One-time configuration failed to pass section validation"
msgstr ""

#: fwbackups/config.py:507
#, python-format
msgid "'%(a)s' is not a one-time configuration file."
msgstr ""

#: fwbackups/config.py:511
msgid ""
"Configuration section 'General' in the one-time configuration file failed to "
"validate"
msgstr ""

#: fwbackups/config.py:523
#, python-format
msgid "Unknown option key '%s' present in one-time backup configuration file"
msgstr ""

#: fwbackups/config.py:528
#, python-format
msgid ""
"Configuration section 'Options' in the one-time backup configuration file "
"failed to validate: Missing options '%s'"
msgstr ""

#: fwbackups/config.py:632
msgid "Restore configuration failed to pass section validation"
msgstr ""

#: fwbackups/config.py:635
#, python-format
msgid "'%(a)s' is not a restore configuration file."
msgstr ""

#: fwbackups/config.py:639
msgid ""
"Configuration section 'General' in the restore configuration file failed to "
"validate"
msgstr ""

#: fwbackups/config.py:649
#, python-format
msgid "Unknown option key '%s' present in restore configuration file"
msgstr ""

#: fwbackups/config.py:654
#, python-format
msgid ""
"Configuration section 'Options' in the restore configuration file failed to "
"validate: Missing options '%s'"
msgstr ""

#: fwbackups/config.py:738
msgid "Preferences failed to pass section validation"
msgstr ""

#: fwbackups/config.py:741
#, fuzzy, python-brace-format
msgid "'{constants.PREFSLOC}' is not a fwbackups preferences file."
msgstr "'%(a)s' er ikke ei innstillingsfil for fwbackups."

#: fwbackups/config.py:745
msgid ""
"Configuration section 'General' in the preferences file failed to validate"
msgstr ""

#: fwbackups/config.py:755
#, python-format
msgid "Unknown option key '%s' present in preferences file"
msgstr ""

#: fwbackups/config.py:760
#, python-format
msgid ""
"Configuration section 'Options' in the preferences file failed to validate: "
"Missing options '%s'"
msgstr ""

#: fwbackups/fwlogger.py:73
#, python-format
msgid "Could not set up the logger: %s"
msgstr ""

#: fwbackups/operations/__init__.py:62
msgid "Canceling the current operation!"
msgstr "Avbryter pågående operasjon!"

#: fwbackups/operations/__init__.py:66
#, python-format
msgid "Stopping process with ID %s"
msgstr "Stopper prosessen med ID %s"

#: fwbackups/operations/__init__.py:69
#, fuzzy, python-format
msgid "Could not stop process %s: %s"
msgstr "Kunne ikke stoppe prosessen %(a)s: %(b)s"

#: fwbackups/operations/__init__.py:77
msgid "The operation has been cancelled."
msgstr "Operasjonen har blitt avbrutt."

#: fwbackups/operations/__init__.py:90
#, python-format
msgid "Error handling file `%s'"
msgstr ""

#: fwbackups/operations/__init__.py:91
#, python-format
msgid ""
"Output:\n"
"%s"
msgstr ""

#: fwbackups/operations/__init__.py:96
#, python-format
msgid "Destination folder `%s' exists"
msgstr ""

#: fwbackups/operations/__init__.py:101
#, python-format
msgid "Created destination folder `%s'"
msgstr ""

#: fwbackups/operations/__init__.py:103
#, python-format
msgid "The destination folder `%(a)s' could not be created: %(b)s"
msgstr ""

#: fwbackups/operations/__init__.py:107
#, python-format
msgid ""
"You do not have read and write permissions on the destination `%s' - if you "
"backed up system files, this operation may fail."
msgstr ""

#: fwbackups/operations/backup.py:86
msgid "rpm - Package list"
msgstr ""

#: fwbackups/operations/backup.py:105
msgid "Pacman - Package list"
msgstr ""

#: fwbackups/operations/backup.py:111
msgid "dpkg - Package list"
msgstr ""

#: fwbackups/operations/backup.py:121
msgid "Disk Information"
msgstr "Diskinformasjon"

#: fwbackups/operations/backup.py:189
#, python-format
msgid "Attempting to connect to server %s..."
msgstr "Prøver å koble til tjeneren %s…"

#: fwbackups/operations/backup.py:200
msgid "Attempt to connect succeeded."
msgstr "Tilkoblet."

#: fwbackups/operations/backup.py:203
msgid ""
"The backup destination was either not found or it cannot be written to due "
"to insufficient permissions."
msgstr ""

#: fwbackups/operations/backup.py:207 fwbackups/operations/restore.py:93
msgid ""
"A connection was established, but authentication failed. Please verify the "
"username and password and try again."
msgstr ""

#: fwbackups/operations/backup.py:212 fwbackups/operations/restore.py:98
#, python-format
msgid ""
"A connection to the server could not be established.\n"
"Error %(a)s: %(b)s"
msgstr ""

#: fwbackups/operations/backup.py:217 fwbackups/operations/restore.py:103
msgid ""
"A connection to the server has timed out. Please verify your settings and "
"try again."
msgstr ""

#: fwbackups/operations/backup.py:221 fwbackups/operations/restore.py:107
#, python-format
msgid ""
"A connection to the server could not be established because an error "
"occurred: %s"
msgstr ""

#: fwbackups/operations/backup.py:239 fwbackups/operations/backup.py:277
#: fwbackups/operations/backup.py:320
#, python-format
msgid ""
"Using %s on Windows: Cancel function will only take effect after a path has "
"been completed."
msgstr ""

#. let's deal with real paths
#: fwbackups/operations/backup.py:245 fwbackups/operations/backup.py:283
#: fwbackups/operations/backup.py:293 fwbackups/operations/backup.py:326
#: fwbackups/operations/backup.py:336 fwbackups/operations/backup.py:372
#: fwbackups/operations/backup.py:384
#, python-format
msgid "Backing up path %(a)i/%(b)i: %(c)s"
msgstr ""

#: fwbackups/operations/backup.py:253
#, python-format
msgid "Running command: nice -n %(a)i %(b)s '%(c)s'"
msgstr ""

#: fwbackups/operations/backup.py:256 fwbackups/operations/backup.py:298
#: fwbackups/operations/backup.py:341 fwbackups/operations/backup.py:391
#: fwbackups/operations/backup.py:598
#, python-format
msgid "Starting subprocess with PID %s"
msgstr "Starter underprosess med PID %s"

#: fwbackups/operations/backup.py:267 fwbackups/operations/backup.py:310
#: fwbackups/operations/backup.py:353 fwbackups/operations/backup.py:403
#, python-format
msgid "Subprocess with PID %(a)s exited with status %(b)s"
msgstr ""

#: fwbackups/operations/backup.py:272 fwbackups/operations/backup.py:315
#: fwbackups/operations/backup.py:358 fwbackups/operations/backup.py:409
#: fwbackups/operations/backup.py:613
#, python-format
msgid "Process exited with status %(a)s. Errors: %(b)s"
msgstr ""

#: fwbackups/operations/backup.py:285 fwbackups/operations/backup.py:328
#, python-format
msgid "Adding path `%s' to the archive"
msgstr ""

#: fwbackups/operations/backup.py:292 fwbackups/operations/backup.py:335
#, python-format
msgid ""
"Using %s: Must backup all paths at once - Progress notification will be "
"disabled."
msgstr ""

#: fwbackups/operations/backup.py:294 fwbackups/operations/backup.py:337
#, python-format
msgid "Running command: nice -n %(a)i %(b)s %(c)s"
msgstr ""

#: fwbackups/operations/backup.py:374
#, python-format
msgid ""
"Path %s is missing or cannot be read and will be excluded from the backup."
msgstr ""

#: fwbackups/operations/backup.py:388
#, python-format
msgid "Running command: nice -n %(a)i %(b)s %(c)s '%(d)s'"
msgstr ""

#: fwbackups/operations/backup.py:415
msgid "Sending files to server via SFTP"
msgstr ""

#: fwbackups/operations/backup.py:425
msgid "Could not send file(s) or folder to server:"
msgstr ""

#: fwbackups/operations/backup.py:439
msgid "This function is designed to be subclassed"
msgstr ""

#: fwbackups/operations/backup.py:450
msgid "Starting one-time backup operation"
msgstr ""

#. fmt: Backup-SetName from Backup-Setname-2009-03-22_20-46[.tar[.gz|.bz2]]
#: fwbackups/operations/backup.py:455 fwbackups/operations/backup.py:527
#: fwbackups/operations/backup.py:625 fwbackups/ui/__init__.py:1501
#: fwbackups/ui/__init__.py:1564 fwbackups/ui/__init__.py:1566
msgid "Backup"
msgstr ""

#: fwbackups/operations/backup.py:455
msgid "OneTime"
msgstr ""

#: fwbackups/operations/backup.py:469 fwbackups/operations/backup.py:674
msgid "There are no paths to backup!"
msgstr ""

#: fwbackups/operations/backup.py:487 fwbackups/operations/backup.py:689
#, python-format
msgid "`%s' exists and will be overwritten."
msgstr ""

#. might be ntfs
#. All done!
#: fwbackups/operations/backup.py:508
msgid "Finished one-time backup"
msgstr ""

#. Execute the command
#: fwbackups/operations/backup.py:595
#, python-format
msgid "Executing '%s' command"
msgstr ""

#: fwbackups/operations/backup.py:612
msgid "Command returned with a non-zero exit status!"
msgstr ""

#: fwbackups/operations/backup.py:633
#, python-format
msgid "Removing old backup `%(a)s' on %(b)s"
msgstr ""

#: fwbackups/operations/backup.py:640 fwbackups/operations/backup.py:653
#, python-format
msgid "Removing old backup `%s'"
msgstr "Fjerner gammel sikkerhetskopi  `%s'"

#. oldIncrementalBackup = rsync
#: fwbackups/operations/backup.py:646
#, python-format
msgid "Moving  `%s' to `%s'"
msgstr "Flytter  `%s' til `%s'"

#. source = is not a rsync backup - remove it and start fresh
#: fwbackups/operations/backup.py:649
#, python-format
msgid "`%s' is not an rsync backup - removing."
msgstr ""

#: fwbackups/operations/backup.py:662
#, python-format
msgid "Starting automatic backup operation of set `%s'"
msgstr ""

#: fwbackups/operations/backup.py:727 fwbackups/ui/__init__.py:2277
#: fwbackups/ui/__init__.py:2435
msgid "There was an error while performing the backup!"
msgstr "Feil under sikkerhetskopiering!"

#. All done!
#: fwbackups/operations/backup.py:739
#, python-format
msgid "Finished automatic backup operation of set '%s'"
msgstr ""

#: fwbackups/operations/restore.py:47
msgid "Starting restore operation"
msgstr "Starter gjenopprettingsoperasjon"

#. check if server settings are OK
#: fwbackups/operations/restore.py:76
msgid "Attempting to connect to server"
msgstr ""

#: fwbackups/operations/restore.py:89
msgid ""
"The restore source was either not found or it cannot be read due to "
"insufficient permissions."
msgstr ""

#: fwbackups/operations/restore.py:121
msgid "Receiving files from server"
msgstr "Mottar filer fra tjener"

#: fwbackups/operations/restore.py:132
#, python-format
msgid "Could not receive file from server: %s"
msgstr ""

#. We are dealing with a remote folder - our job here is done
#. Either that or an error was encountered above
#. All done!
#: fwbackups/operations/restore.py:137 fwbackups/operations/restore.py:182
msgid "Finished restore operation"
msgstr "Fullførte gjenopprettingsoperasjon"

#. oops, something is up
#: fwbackups/operations/restore.py:149
#, python-format
msgid "Source `%s' is not a file or folder!"
msgstr "Kilden `%s' er ikke ei fil eller mappe!"

#. oops, something is up
#: fwbackups/operations/restore.py:158
#, python-format
msgid "Source `%s' is not an archive!"
msgstr "Kilden `%s' er ikke et arkiv!"

#: fwbackups/operations/restore.py:162
#, python-format
msgid "Source `%s' is not a folder"
msgstr "Kilden `%s' er ikke ei mappe"

#: fwbackups/operations/restore.py:178
#, python-format
msgid "Traceback: %s"
msgstr ""

#: fwbackups/sftp.py:226
#, python-format
msgid "`%s' is not a file, folder or link! Skipping."
msgstr ""

#: fwbackups/sftp.py:231
msgid "Could not copy some files due to errors:"
msgstr ""

#: fwbackups/shutil_modded.py:136
#, python-format
msgid "`%s' isn't a file, folder or link! Skipping."
msgstr ""

#: fwbackups/shutil_modded.py:147
msgid "Couldn't copy some files due to errors:"
msgstr ""

#: fwbackups/ui/__init__.py:226
#, fuzzy, python-format
msgid "<b>Welcome</b>, %s"
msgstr "<b>Velkommen</b>"

#. done in main3Refresh() #self.ui.main3DestinationTypeCombobox.set_active(0)
#. Default Labels...
#: fwbackups/ui/__init__.py:229 fwbackups/ui/__init__.py:1193
#: fwbackups/ui/__init__.py:1298 fwbackups/ui/__init__.py:1680
msgid "Idle"
msgstr ""

#. Default progressbars...
#: fwbackups/ui/__init__.py:234 fwbackups/ui/__init__.py:1192
msgid "Click 'Backup Set Now' to begin"
msgstr ""

#: fwbackups/ui/__init__.py:235
msgid "Click 'Start Backup' to begin"
msgstr "Klikk 'Start sikkerhetskopiering' for å begynne"

#: fwbackups/ui/__init__.py:236
msgid "Click 'Start Restore' to begin"
msgstr "Klikk 'Start gjenoppretting' for å begynne"

#: fwbackups/ui/__init__.py:263
msgid "Could not setup the fwbackups configuration folder"
msgstr "Fikk ikke til å lage oppsettsmappa for fwbackups"

#: fwbackups/ui/__init__.py:264 fwbackups/ui/__init__.py:302
#, python-format
msgid "The following error occured: %s"
msgstr "Følgende feil inntraff: %s"

#: fwbackups/ui/__init__.py:271
#, python-format
msgid "Validation error: %s"
msgstr "Bekreftelsesfeil: %s"

#: fwbackups/ui/__init__.py:272
msgid "Preferences could not be read"
msgstr "Kunne ikke lese innstillingene"

#: fwbackups/ui/__init__.py:272
msgid ""
"The preferences file may be corrupted and could not be read by fwbackups. "
"Would you like to initialize a new one from the default values? If not, "
"fwbackups will exit."
msgstr ""

#: fwbackups/ui/__init__.py:301
msgid "Could not setup the logger"
msgstr ""

#: fwbackups/ui/__init__.py:325
msgid "Previous installation of fwbackups 1.42.x or older detected"
msgstr "Oppdaget tidligere installasjon av fwbackups 1.42.x eller eldre"

#: fwbackups/ui/__init__.py:325
msgid ""
"Because of certain major changes in fwbackups, your configuration must be "
"imported manually. To do this, run fwbackups as the root user and select "
"<i>File > Import</i> from the menu to import your old configuration.\n"
"If this action is not completed, the backups from version 1.42.x <b>will not "
"run automatically</b>.\n"
"<i>Tip: The 1.42.x configuration was stored in /etc/fwbackups</i>."
msgstr ""

#: fwbackups/ui/__init__.py:332
msgid "A backup of /etc/crontab could not be created"
msgstr "Kunne ikke opprette sikkerhetskopi av /etc/crontab"

#: fwbackups/ui/__init__.py:332
msgid ""
"You may wish to edit /etc/crontab manually and remove any fwbackups-related "
"lines."
msgstr ""

#: fwbackups/ui/__init__.py:333
msgid "Could not create a backup of /etc/crontab; refusing to clean up."
msgstr ""

#: fwbackups/ui/__init__.py:336
msgid "Cleaning up /etc/crontab from previous installation of fwbackups"
msgstr ""

#: fwbackups/ui/__init__.py:345
#, python-format
msgid ""
"fwbackups was unable to clean up the system crontab: %s. You may wish to "
"edit /etc/crontab manually and remove any fwbackups-related lines."
msgstr ""

#: fwbackups/ui/__init__.py:346
msgid "Cleanup of the system crontab failed"
msgstr ""

#: fwbackups/ui/__init__.py:351
msgid "fwbackups administrator started"
msgstr ""

#: fwbackups/ui/__init__.py:360
msgid "Would you like to clean up the log file?"
msgstr ""

#: fwbackups/ui/__init__.py:360
#, python-format
msgid ""
"The log file is becoming large (%s). Would you like to clear it? This will "
"permanently remove all entries from the log."
msgstr ""

#: fwbackups/ui/__init__.py:478
msgid "Regenerating crontab"
msgstr ""

#: fwbackups/ui/__init__.py:479
msgid "Please wait... Regenerating crontab"
msgstr ""

#: fwbackups/ui/__init__.py:492
#, python-format
msgid "Could not parse the configuration for set '%s'"
msgstr ""

#: fwbackups/ui/__init__.py:493
#, python-format
msgid ""
"The set configuration file '%s' failed to validate, so it may not be "
"properly scheduled. Other sets are unaffected by this error."
msgstr ""

#: fwbackups/ui/__init__.py:500
#, python-format
msgid ""
"Internal error: generated entry for set '%s' was not parsable. Please submit "
"a bug report."
msgstr ""

#: fwbackups/ui/__init__.py:503
#, python-format
msgid "Could not schedule automated backups for set '%s'"
msgstr ""

#: fwbackups/ui/__init__.py:504
msgid ""
"fwbackups could not regenerate a crontab entry because an error occured:\n"
msgstr ""

#: fwbackups/ui/__init__.py:505
#, python-format
msgid ""
"%(a)s\n"
"\n"
"The crontab entry associated with the error was:\n"
"%(b)s"
msgstr ""

#. After all is done, log an message
#: fwbackups/ui/__init__.py:508
#, python-format
msgid "Saving set `%s' to the crontab"
msgstr ""

#: fwbackups/ui/__init__.py:520
#, python-format
msgid "Unable to write new crontab: %s"
msgstr ""

#: fwbackups/ui/__init__.py:521
msgid "Error saving backup schedule to crontab"
msgstr ""

#: fwbackups/ui/__init__.py:521
msgid ""
"Changes made to the backup schedule may not have been correctly saved. If "
"you are using custom cron entry for a backup set, verify the values are "
"valid.\n"
"\n"
msgstr ""

#: fwbackups/ui/__init__.py:525
msgid ""
"A backup of the crontab was restored; the latest changes to the backup "
"schedule not have been saved."
msgstr ""

#: fwbackups/ui/__init__.py:527
#, fuzzy, python-brace-format
msgid "A backup of the crontab could not be restored: {error}"
msgstr "Kunne ikke opprette sikkerhetskopi av /etc/crontab"

#: fwbackups/ui/__init__.py:533
msgid "fwbackups is working"
msgstr "fwbackups arbeider"

#: fwbackups/ui/__init__.py:534
msgid ""
"An operation is currently in progress. Would you like to cancel it and quit "
"anyways?"
msgstr ""

#: fwbackups/ui/__init__.py:536
msgid "Please wait... Canceling operations"
msgstr "Vent… Avbryter operasjoner"

#: fwbackups/ui/__init__.py:549
msgid "fwbackups detected more than one alive threads!"
msgstr ""

#: fwbackups/ui/__init__.py:554
#, python-format
msgid "Closed dead Paramiko thread: %s"
msgstr ""

#. FIXME: Figure out how to kill other thread types. For now, just log.
#: fwbackups/ui/__init__.py:557
#, python-format
msgid "Could not close thread %s!"
msgstr ""

#: fwbackups/ui/__init__.py:558
msgid "Please submit a bug report and include this message."
msgstr ""

#: fwbackups/ui/__init__.py:567 fwbackups/ui/__init__.py:2192
msgid "Could not save backup schedule"
msgstr ""

#: fwbackups/ui/__init__.py:567
msgid ""
"fwbackups was unable to save the backup scheduling information to the "
"crontab. If you are using manual times entry in one of your sets, please "
"verify that all five fields are using the correct syntax."
msgstr ""

#. Shutdown logging & quit the GTK mainloop
#: fwbackups/ui/__init__.py:569
msgid "fwbackups administrator closed"
msgstr ""

#: fwbackups/ui/__init__.py:580
msgid "Creating thread"
msgstr "Oppretter tråd"

#: fwbackups/ui/__init__.py:581
msgid "testConnection(): Creating thread"
msgstr "testConnection(): Oppretter tråd"

#: fwbackups/ui/__init__.py:584
msgid "Attempting to connect"
msgstr "Prøver å koble til"

#: fwbackups/ui/__init__.py:588
#, python-format
msgid "testConnection(): Thread returning with retval %s"
msgstr ""

#: fwbackups/ui/__init__.py:590
msgid "Success!"
msgstr ""

#: fwbackups/ui/__init__.py:590
#, python-format
msgid "fwbackups was able to connect and authenticate on '%s'."
msgstr ""

#: fwbackups/ui/__init__.py:592
msgid "Remote destination is not usable"
msgstr ""

#: fwbackups/ui/__init__.py:592
#, python-format
msgid ""
"The folder '%(a)s' on '%(b)s' either does not exist or it is not a folder. "
"Please verify your settings and try again."
msgstr ""

#: fwbackups/ui/__init__.py:594 fwbackups/ui/__init__.py:1469
msgid "Authentication failed"
msgstr ""

#: fwbackups/ui/__init__.py:594
#, python-format
msgid ""
"A connection to '%s' was established, but authentication failed. Please "
"verify the username and password and try again."
msgstr ""

#: fwbackups/ui/__init__.py:596 fwbackups/ui/__init__.py:600
#, python-format
msgid "A connection to '%s' could not be established"
msgstr "Kunne ikke etablere tilkobling til '%s'"

#: fwbackups/ui/__init__.py:596
#, python-format
msgid "Error %(a)s: %(b)s"
msgstr "Feil %(a)s: %(b)s"

#: fwbackups/ui/__init__.py:598
#, python-format
msgid "The server '%s' is not responding"
msgstr "Tjeneren '%s' svarer ikke"

#: fwbackups/ui/__init__.py:598 fwbackups/ui/__init__.py:1476
msgid "Please verify your settings and try again."
msgstr "Bekreft innstillingene dine og prøv igjen."

#: fwbackups/ui/__init__.py:600
#, python-format
msgid "Error: %s. Please verify your settings and try again."
msgstr "Feil: %s. Bekreft innstillingene dine og prøv igjen."

#: fwbackups/ui/__init__.py:602 fwbackups/ui/__init__.py:1168
#: fwbackups/ui/__init__.py:1481
msgid "Unexpected error"
msgstr "Uventet feil"

#: fwbackups/ui/__init__.py:602
msgid "An unknown error occurred while testing for connectivity."
msgstr ""

#: fwbackups/ui/__init__.py:615 fwbackups/ui/__init__.py:618
#: fwbackups/ui/__init__.py:903 fwbackups/widgets.py:619
#: fwbackups/widgets.py:622
msgid "Choose file(s)"
msgstr ""

#: fwbackups/ui/__init__.py:617 fwbackups/ui/__init__.py:699
#: fwbackups/ui/__init__.py:905 fwbackups/ui/__init__.py:975
#: fwbackups/ui/__init__.py:1334 fwbackups/ui/__init__.py:1694
#: fwbackups/ui/__init__.py:1708 fwbackups/ui/__init__.py:1722
#: fwbackups/widgets.py:621 fwbackups/widgets.py:633
msgid "_Open"
msgstr ""

#: fwbackups/ui/__init__.py:617 fwbackups/ui/__init__.py:699
#: fwbackups/ui/__init__.py:905 fwbackups/ui/__init__.py:975
#: fwbackups/ui/__init__.py:1334 fwbackups/ui/__init__.py:1694
#: fwbackups/ui/__init__.py:1708 fwbackups/ui/__init__.py:1722
#: fwbackups/widgets.py:621 fwbackups/widgets.py:633 fwbackups/widgets.py:740
#, fuzzy
msgid "_Cancel"
msgstr "Avbryter…"

#: fwbackups/ui/__init__.py:619
msgid "Configuration files (*.conf)"
msgstr "Oppsettsfiler (*.conf)"

#: fwbackups/ui/__init__.py:680
msgid "File Exists"
msgstr "Fila finnes"

#: fwbackups/ui/__init__.py:681
#, python-format
msgid "'%s.conf' already exists! Would you like to overwrite it?"
msgstr "'%s.conf' finnes allerede! Ønsker du å overskrive den?"

#: fwbackups/ui/__init__.py:687
#, python-format
msgid "Exported set `%(a)s' to `%(b)s'"
msgstr ""

#: fwbackups/ui/__init__.py:697 fwbackups/ui/__init__.py:700
#: fwbackups/ui/__init__.py:906 fwbackups/ui/__init__.py:973
#: fwbackups/ui/__init__.py:976 fwbackups/ui/__init__.py:1332
#: fwbackups/ui/__init__.py:1335 fwbackups/widgets.py:631
#: fwbackups/widgets.py:634
msgid "Choose folder(s)"
msgstr ""

#: fwbackups/ui/__init__.py:707
msgid "Sets exported"
msgstr ""

#: fwbackups/ui/__init__.py:707
msgid "The selected sets were exported successfully."
msgstr ""

#: fwbackups/ui/__init__.py:734 fwbackups/ui/__init__.py:1119
#: fwbackups/ui/__init__.py:1136 fwbackups/ui/__init__.py:1210
#: fwbackups/ui/__init__.py:2247
msgid "No set has been selected"
msgstr ""

#: fwbackups/ui/__init__.py:734
msgid "You must select a set to duplicate."
msgstr ""

#: fwbackups/ui/__init__.py:738
msgid "_copy"
msgstr "_kopier"

#: fwbackups/ui/__init__.py:892
#, python-format
msgid "Resetting preference '%(a)s' to 0"
msgstr "Tilbakestiller innstillingen '%(a)s' til 0"

#: fwbackups/ui/__init__.py:993 fwbackups/ui/__init__.py:1256
#: fwbackups/ui/__init__.py:1261 fwbackups/ui/__init__.py:1352
#: fwbackups/ui/__init__.py:1535 fwbackups/ui/__init__.py:1610
#: fwbackups/ui/__init__.py:1647 fwbackups/ui/__init__.py:2152
#: fwbackups/ui/__init__.py:2157
msgid "Missing information"
msgstr "Manglende informasjon"

#: fwbackups/ui/__init__.py:993
msgid "Please complete the host, username, folder and port fields."
msgstr ""

#: fwbackups/ui/__init__.py:1119
msgid "You must select a set to edit."
msgstr ""

#: fwbackups/ui/__init__.py:1136
msgid "You must select a set to remove."
msgstr ""

#: fwbackups/ui/__init__.py:1138
#, python-format
msgid "Delete backup set '%s'?"
msgstr ""

#: fwbackups/ui/__init__.py:1138
msgid ""
"This action will permanently delete the backup set configuration. This "
"action will not delete any existing backups, or files and folders associated "
"with the set."
msgstr ""

#: fwbackups/ui/__init__.py:1145 fwbackups/ui/__init__.py:1153
#, python-format
msgid ""
"An error occured while removing set `%(a)s':\n"
"%(b)s"
msgstr ""

#: fwbackups/ui/__init__.py:1146
#, python-format
msgid "Could not remove backup set '%s'"
msgstr ""

#: fwbackups/ui/__init__.py:1154
#, python-format
msgid "Could not remove the automated backup schedule for set '%s'"
msgstr ""

#: fwbackups/ui/__init__.py:1158
#, python-format
msgid "Removing set `%s'"
msgstr ""

#: fwbackups/ui/__init__.py:1168
#, python-format
msgid ""
"An unexpected error occured while attempting to obtain the selected set:\n"
"%s"
msgstr ""

#: fwbackups/ui/__init__.py:1210
msgid "You must select a set to restore."
msgstr ""

#: fwbackups/ui/__init__.py:1256 fwbackups/ui/__init__.py:2152
msgid "Please fill in the Folder field."
msgstr ""

#: fwbackups/ui/__init__.py:1261 fwbackups/ui/__init__.py:2157
msgid "Please fill in the Host, Username, Port and Folder fields."
msgstr ""

#: fwbackups/ui/__init__.py:1352 fwbackups/ui/__init__.py:1535
#: fwbackups/ui/__init__.py:1647
msgid "Please complete all of the host, username, folder and port fields."
msgstr ""

#: fwbackups/ui/__init__.py:1376
msgid "Log cleared"
msgstr "Logg tømt"

#: fwbackups/ui/__init__.py:1381
msgid "Clear the old log entries?"
msgstr ""

#: fwbackups/ui/__init__.py:1382
msgid "This action will permanently remove all log entries."
msgstr ""

#: fwbackups/ui/__init__.py:1400
#, python-format
msgid "Log saved to file `%s'"
msgstr "Logg lagret til fila '%s'"

#: fwbackups/ui/__init__.py:1466
msgid "Previous backups could not be found"
msgstr ""

#: fwbackups/ui/__init__.py:1467
#, python-format
msgid "The destination folder for set '%s' was not found."
msgstr ""

#: fwbackups/ui/__init__.py:1470
#, python-format
msgid ""
"fwbackups was unable to authenticate on the remote server. Please verify the "
"username and password for set '%s' and try again."
msgstr ""

#: fwbackups/ui/__init__.py:1472 fwbackups/ui/__init__.py:1478
msgid "Connection failed"
msgstr "Tilkobling mislyktes"

#: fwbackups/ui/__init__.py:1473
#, python-format
msgid ""
"A connection to the server could not be established:\n"
"Error %(a)s: %(b)s\n"
"Please verify your settings and try again."
msgstr ""

#: fwbackups/ui/__init__.py:1475
msgid "Remote server is not responding"
msgstr ""

#: fwbackups/ui/__init__.py:1479
#, python-format
msgid ""
"A connection to the server could not be established because an error "
"occurred: %s\n"
"Please verify your settings and try again."
msgstr ""

#: fwbackups/ui/__init__.py:1493
#, python-format
msgid ""
"Error obtaining file listing in destination %(a)s:\n"
"%(b)s"
msgstr ""

#: fwbackups/ui/__init__.py:1494
#, python-format
msgid "Could not get a list of old backups for set '%s'"
msgstr ""

#: fwbackups/ui/__init__.py:1494
msgid ""
"If the destination is on removable media such as an external hard disk, "
"please attach it and try again."
msgstr ""

#. We can't start a restore if there are no set dates
#: fwbackups/ui/__init__.py:1504 fwbackups/ui/__init__.py:1618
#: fwbackups/ui/__init__.py:1619
msgid "No backups found"
msgstr "Fant ingen sikkerhetskopier"

#: fwbackups/ui/__init__.py:1610
msgid "Please select a backup date."
msgstr "Velg en dato for sikkerhetskopiering"

#: fwbackups/ui/__init__.py:1619
#, python-format
msgid ""
"The backup set '%s' does not have any stored backups yet! Choose another "
"set, or alternatively choose a different restore source."
msgstr ""

#: fwbackups/ui/__init__.py:1626 fwbackups/ui/__init__.py:1637
msgid "Restore source"
msgstr "Gjenopprett kilde"

#: fwbackups/ui/__init__.py:1626
msgid "Please enter the location of the local archive."
msgstr ""

#: fwbackups/ui/__init__.py:1629
msgid "Wrong file type"
msgstr "Feil filtype"

#: fwbackups/ui/__init__.py:1630
msgid ""
"The file you selected is not a supported archive.\n"
"Supported archives types are tar with no, gzip or bzip2 compression."
msgstr ""

#: fwbackups/ui/__init__.py:1637
msgid "Please enter the location of the local folder."
msgstr ""

#: fwbackups/ui/__init__.py:1692 fwbackups/ui/__init__.py:1695
#: fwbackups/ui/__init__.py:1706 fwbackups/ui/__init__.py:1709
#: fwbackups/ui/__init__.py:1720 fwbackups/ui/__init__.py:1723
msgid "Select a Folder"
msgstr "Velg ei mappe"

#: fwbackups/ui/__init__.py:1737 fwbackups/ui/__init__.py:1740
msgid "Invalid set name"
msgstr ""

#: fwbackups/ui/__init__.py:1737
msgid "Please enter a set name."
msgstr ""

#: fwbackups/ui/__init__.py:1740
msgid ""
"'temporary_name' is a reserved name. Please choose another name for the set."
msgstr ""

#: fwbackups/ui/__init__.py:1744
#, python-format
msgid "Overwrite settings for set '%s'?"
msgstr ""

#: fwbackups/ui/__init__.py:1745
msgid ""
"This will overwrite the stored settings with the current ones. Are you sure "
"you want to continue?"
msgstr ""

#: fwbackups/ui/__init__.py:1856
msgid "Error parsing configuration file"
msgstr ""

#: fwbackups/ui/__init__.py:1857
msgid "fwbackups will using the default times instead."
msgstr ""

#: fwbackups/ui/__init__.py:1870
#, python-format
msgid "Unknown destination type `%s'"
msgstr "Ukjent måltype '%s'"

#: fwbackups/ui/__init__.py:2072
msgid "Error creating the automated backup schedules"
msgstr ""

#: fwbackups/ui/__init__.py:2073
#, python-format
msgid ""
"The crontab could not be written because an error occured:\n"
"%s"
msgstr ""

#: fwbackups/ui/__init__.py:2108 fwbackups/widgets.py:712
msgid "Parsing configuration files"
msgstr "Tolker oppsettsfiler"

#: fwbackups/ui/__init__.py:2123 fwbackups/widgets.py:718
#, python-format
msgid "Refusing to parse file `%s': configuration files must end in `.conf'"
msgstr ""

#: fwbackups/ui/__init__.py:2175
#, python-format
msgid "Renaming set `%(a)s' to `%(b)s"
msgstr ""

#: fwbackups/ui/__init__.py:2177
#, python-format
msgid "Renaming set `%(a)s' to `%(b)s failed: %(c)s"
msgstr ""

#: fwbackups/ui/__init__.py:2178
#, python-format
msgid "Could not rename set '%(a)s' to '%(b)s'"
msgstr ""

#. creating a set
#: fwbackups/ui/__init__.py:2184
#, python-format
msgid "Creating set `%s'"
msgstr ""

#. editing a set
#: fwbackups/ui/__init__.py:2188
#, python-format
msgid "Saving changes to set `%s'"
msgstr ""

#: fwbackups/ui/__init__.py:2192
msgid ""
"Your set configuration changes were saved, but fwbackups was unable to save "
"the backup scheduling information to the crontab. If you are using manual "
"times entry, please verify that all five fields are using the correct syntax."
msgstr ""

#: fwbackups/ui/__init__.py:2230 fwbackups/ui/__init__.py:2391
#, python-format
msgid "[%(a)i/%(b)i] Backing up: %(c)s"
msgstr ""

#: fwbackups/ui/__init__.py:2233 fwbackups/ui/__init__.py:2394
#, python-format
msgid "[%(a)i/%(b)i] Backing up files... Please wait"
msgstr ""

#: fwbackups/ui/__init__.py:2235 fwbackups/ui/__init__.py:2396
msgid "Cleaning old backups"
msgstr ""

#: fwbackups/ui/__init__.py:2237 fwbackups/ui/__init__.py:2398
msgid "Sending files to remote server"
msgstr ""

#: fwbackups/ui/__init__.py:2239 fwbackups/ui/__init__.py:2400
msgid "Executing user command"
msgstr ""

#: fwbackups/ui/__init__.py:2247
msgid "You must select to initiate a manual set backup."
msgstr ""

#: fwbackups/ui/__init__.py:2253 fwbackups/ui/__init__.py:2409
#: fwbackups/ui/__init__.py:2499
msgid "Initializing"
msgstr ""

#: fwbackups/ui/__init__.py:2255 fwbackups/ui/__init__.py:2411
#, fuzzy
msgid "Backup started"
msgstr "Sikkerhetskopiering mislyktes!"

#: fwbackups/ui/__init__.py:2255
#, python-format
msgid "Starting a set backup operation of '%(a)s'"
msgstr ""

#: fwbackups/ui/__init__.py:2258 fwbackups/ui/__init__.py:2316
#: fwbackups/ui/__init__.py:2418 fwbackups/ui/__init__.py:2478
#: fwbackups/ui/__init__.py:2504 fwbackups/ui/__init__.py:2562
msgid "Please wait..."
msgstr "Vent…"

#: fwbackups/ui/__init__.py:2264 fwbackups/ui/__init__.py:2422
#: fwbackups/ui/__init__.py:2509
msgid "Working"
msgstr "Arbeider"

#. thread returned
#: fwbackups/ui/__init__.py:2272 fwbackups/ui/__init__.py:2430
#: fwbackups/ui/__init__.py:2517
#, python-format
msgid "Thread returned with retval %s"
msgstr ""

#. error
#: fwbackups/ui/__init__.py:2281 fwbackups/ui/__init__.py:2299
#: fwbackups/ui/__init__.py:2439 fwbackups/ui/__init__.py:2458
#: fwbackups/ui/__init__.py:2523 fwbackups/ui/__init__.py:2543
msgid "<span color=\"Red\">Error</span>"
msgstr "<span color=\"Red\">Feil</span>"

#: fwbackups/ui/__init__.py:2282 fwbackups/ui/__init__.py:2443
#, python-format
msgid "An error occurred while initializing the backup operation: %s"
msgstr ""

#: fwbackups/ui/__init__.py:2286 fwbackups/ui/__init__.py:2444
msgid "Error initializing backup"
msgstr ""

#: fwbackups/ui/__init__.py:2296 fwbackups/ui/__init__.py:2455
#, fuzzy
msgid "Backup complete"
msgstr "Sikkerhetskopiering mislyktes!"

#: fwbackups/ui/__init__.py:2296
#, python-format
msgid "Finished the automatic backup operation of set `%(a)s'"
msgstr ""

#: fwbackups/ui/__init__.py:2297 fwbackups/ui/__init__.py:2456
#: fwbackups/ui/__init__.py:2540
msgid "<span color=\"dark green\">Operation complete</span>"
msgstr ""

#: fwbackups/ui/__init__.py:2301 fwbackups/ui/__init__.py:2460
msgid "Error during backup"
msgstr ""

#: fwbackups/ui/__init__.py:2301
#, python-format
msgid ""
"An error occured while performing the automatic backup operation of set "
"`%(a)s'"
msgstr ""

#: fwbackups/ui/__init__.py:2304 fwbackups/ui/__init__.py:2465
#, fuzzy
msgid "Backup cancelled"
msgstr "Sikkerhetskopiering mislyktes!"

#: fwbackups/ui/__init__.py:2304
#, python-format
msgid "The automatic backup operation of set `%(a)s' was cancelled"
msgstr ""

#: fwbackups/ui/__init__.py:2305 fwbackups/ui/__init__.py:2466
#: fwbackups/ui/__init__.py:2551
msgid "<span color=\"red\">Operation cancelled</span>"
msgstr ""

#: fwbackups/ui/__init__.py:2306 fwbackups/ui/__init__.py:2467
#: fwbackups/ui/__init__.py:2552
msgid "Operation cancelled"
msgstr "Operasjon avbrutt"

#: fwbackups/ui/__init__.py:2317 fwbackups/ui/__init__.py:2479
#: fwbackups/ui/__init__.py:2563
msgid "Cancelling..."
msgstr "Avbryter…"

#: fwbackups/ui/__init__.py:2411
msgid "Starting a one-time backup operation"
msgstr ""

#: fwbackups/ui/__init__.py:2455
msgid "Finished the one-time backup operation"
msgstr ""

#: fwbackups/ui/__init__.py:2460
msgid "An error occured while performing the one-time backup operation"
msgstr ""

#: fwbackups/ui/__init__.py:2465
msgid "The one-time backup operation was cancelled"
msgstr ""

#. no "current file" yet
#: fwbackups/ui/__init__.py:2491
msgid "Receiving files from remote server"
msgstr ""

#. we have a 'current file'
#: fwbackups/ui/__init__.py:2493
#, python-format
msgid "Restoring: %s"
msgstr "Gjenoppretter: %s"

#: fwbackups/ui/__init__.py:2501
#, fuzzy
msgid "Restore started"
msgstr "Gjenopprett kilde"

#: fwbackups/ui/__init__.py:2501
msgid "Starting a restore operation"
msgstr ""

#: fwbackups/ui/__init__.py:2519
msgid ""
"There was an error while performing the restore! Enable debug messages for "
"more information."
msgstr ""

#: fwbackups/ui/__init__.py:2526
#, python-format
msgid "An error occurred while initializing the restore operation: %s"
msgstr ""

#: fwbackups/ui/__init__.py:2527
msgid "Error initializing restore operation"
msgstr ""

#: fwbackups/ui/__init__.py:2539
#, fuzzy
msgid "Restore finished"
msgstr "Gjenoppretting mislyktes!"

#: fwbackups/ui/__init__.py:2539
msgid "Finished the restore operation"
msgstr ""

#: fwbackups/ui/__init__.py:2545
msgid "Error during restore"
msgstr ""

#: fwbackups/ui/__init__.py:2545
msgid "An error occured while performing the restore operation"
msgstr ""

#: fwbackups/ui/__init__.py:2550
#, fuzzy
msgid "Restore cancelled"
msgstr "Gjenoppretting mislyktes!"

#: fwbackups/ui/__init__.py:2550
msgid "The restore operation was cancelled"
msgstr "Gjenopprettingsoperasjonen ble avbrutt"

#: fwbackups/widgets.py:149 fwbackups/widgets.py:192
msgid "CRITICAL"
msgstr "KRITISK"

#: fwbackups/widgets.py:149 fwbackups/widgets.py:192
msgid "ERROR"
msgstr "FEIL"

#: fwbackups/widgets.py:151 fwbackups/widgets.py:194
msgid "WARNING"
msgstr "ADVARSEL"

#: fwbackups/widgets.py:164 fwbackups/widgets.py:188
msgid "Previous log messages"
msgstr "Tidligere loggmeldinger"

#: fwbackups/widgets.py:168 fwbackups/widgets.py:201
msgid "No previous log messages to display"
msgstr "Ingen tidligere loggmeldinger å vise"

#: fwbackups/widgets.py:169 fwbackups/widgets.py:180
msgid "Current session's log messages"
msgstr ""

#: fwbackups/widgets.py:536
msgid "Access"
msgstr "Tilgang"

#: fwbackups/widgets.py:542
msgid "Path"
msgstr "Sti"

#: fwbackups/widgets.py:658
msgid "Please select a path before choosing an action."
msgstr ""

#: fwbackups/widgets.py:691
msgid "Export"
msgstr "Eksporter"

#: fwbackups/widgets.py:697
msgid "Set"
msgstr ""

#: fwbackups/widgets.py:732
msgid "Bug Report"
msgstr "Feilrapport"

#: fwbackups/widgets.py:740
msgid "_Save"
msgstr ""

#~ msgid "*** Initializing files"
#~ msgstr "*** henter filer"

#, python-format
#~ msgid ""
#~ "Folder %s exists and will be emptied. Press <Enter> to confirm or "
#~ "<ctrl+c> to cancel..."
#~ msgstr ""
#~ "Mappa %s finnes og vil bli tømt. Trykk <Enter> for å bekrefte eller "
#~ "<Ctrl+c> for å avbryte"

#, python-format
#~ msgid "Cleaning folder %s..."
#~ msgstr "Tømmer mappe %s…"

#~ msgid "*** Remote settings"
#~ msgstr "Fjerinnstillinger"

#~ msgid "Hostname [localhost]: "
#~ msgstr "Vertsnavn [localhost]: "

#~ msgid "Port [22]: "
#~ msgstr "Port [22]: "

#~ msgid "The port field can only contain numbers. Please try again."
#~ msgstr "Porten må være et nummer."

#, python-format
#~ msgid "Username [%s]: "
#~ msgstr "Brukernavn [%s]:"

#~ msgid "Password: "
#~ msgstr "Passord:"

#, python-format
#~ msgid "Remote folder [%s]: "
#~ msgstr "Fjernmappe [%s]:"

#, python-format
#~ msgid "*** Running restore of local test backup %s"
#~ msgstr "Kjører gjenoppretting av lokal test-sikkerhetskopi %s"

#~ msgid "*** Running restore of a local archive"
#~ msgstr "Kjører gjenoppretting av lokalt akriv"

#~ msgid "*** Running restore of a local folder"
#~ msgstr "Kjører gjenoppretting av lokal mappe"

#~ msgid "*** Running restore of a remote archive (SSH)"
#~ msgstr "Kjører gjenoppretting av fjernarkiv (SSH)"

#~ msgid "*** Running restore of a remote folder (SSH)"
#~ msgstr "Kjører gjenoppretting av fjernmappe (SSH)"

#, python-format
#~ msgid "Error: %s"
#~ msgstr "Feil: %s"

#~ msgid "Run with --help for usage information."
#~ msgstr "Kjør med --help for bruksinformasjon."

#~ msgid "Destination type was not specified"
#~ msgstr "Måltype ikke oppgitt"

#~ msgid "Please install pycrypto (python-crypto)"
#~ msgstr "Installer pycrypto (python-crypto)"

#~ msgid "Please install paramiko (python-paramiko)"
#~ msgstr "Installer Paramiko (python-paramiko)"

#, python-format
#~ msgid "<span size=\"small\">%s%% complete: %s</span>"
#~ msgstr "<span size=\"small\">%s%% fullført: %s</span>"

#~ msgid "Checking permissions"
#~ msgstr "Sjekker rettigheter"

#~ msgid "Setting up the logger and user preferences"
#~ msgstr "Setter opp loggføring og bruker-innstillinger"

#~ msgid "Ready!"
#~ msgstr "Klar!"

#~ msgid "Please enter a Pycron installation directory."
#~ msgstr "Velg ei mappe å installere Pycron i."

#~ msgid "Configuration not found"
#~ msgstr "Fant ikke oppsett"

#~ msgid "Automated restore not supported"
#~ msgstr "Automatisk gjenoppretting støttes ikke"

#~ msgid "Status"
#~ msgstr "Status"

#~ msgid "Show this program's version and exit"
#~ msgstr "Vis programversjon og avslutt"

#~ msgid "Show this help message and exit"
#~ msgstr "Vis denne hjelpemeldingen og avslutt"

#~ msgid "print log messages to the terminal. Use this option twice"
#~ msgstr "skriv loggmeldinger til terminalen. Bruk dette valget to ganger"

#~ msgid "start GUI minimized in the system tray"
#~ msgstr "start visuelt brukergrensesnitt i systemkurven"

#~ msgid "_Browse..."
#~ msgstr "_Utforsk…"

#~ msgid ""
#~ "gzip: fast, lightweight\n"
#~ "bzip2: slower, more efficient"
#~ msgstr ""
#~ "gzip: Raskt, lett\n"
#~ "bzip2: Tregere, mer effektivt"

#~ msgid "_Back"
#~ msgstr "_Tilbake"

#~ msgid "_Next"
#~ msgstr "_Neste"

#~ msgid "_Start Backup"
#~ msgstr "_Start sikkerhetskopi"

#~ msgid "<span size=\"large\" weight=\"bold\">Log Viewer</span>"
#~ msgstr "<span size=\"large\" weight=\"bold\">Loggvisning</span>"

#~ msgid "_File"
#~ msgstr "_Fil"

#~ msgid "_View"
#~ msgstr "_Vis"

#~ msgid "Switch to Overview"
#~ msgstr "Bytt til oversikt"

#~ msgid "_Overview"
#~ msgstr "_Oversikt"

#~ msgid "Switch to Log Viewer"
#~ msgstr "Bytt til loggvisning"

#~ msgid "_Log"
#~ msgstr "_Logg"

#~ msgid "Switch to Restore"
#~ msgstr "Bytt til gjenoppretting"

#~ msgid "_Restore"
#~ msgstr "_Gjenopprett"

#~ msgid "_Help"
#~ msgstr "_Hjelp"

#~ msgid "Check for _Updates"
#~ msgstr "Se etter _oppdateringer"

#~ msgid "About fwbackups"
#~ msgstr "Om fwbackups"

#~ msgid "License"
#~ msgstr "Lisens"

#~ msgid "Credits"
#~ msgstr "Bidragsytere"

#~ msgid "Select a file or folder"
#~ msgstr "Velg ei fil eller mappe"

#~ msgid "Save to..."
#~ msgstr "Lagre i…"

#~ msgid "Status: fwbackups is running"
#~ msgstr "Status: Fwbackups kjører"

#~ msgid "_Show Administrator"
#~ msgstr "_Vis administrator"

#~ msgid "_Minimize to tray on close"
#~ msgstr "_Minimer til systemkurv ved lukking"

#~ msgid "Edit preferences"
#~ msgstr "Endre innstillinger"

#~ msgid "_Preferences"
#~ msgstr "_Innstillinger"

#~ msgid "_Quit"
#~ msgstr "_Avslutt"

#~ msgid "Export to:"
#~ msgstr "Eksporter til:"

#~ msgid "Browse..."
#~ msgstr "Utforsk…"

#~ msgid "Start _Restore"
#~ msgstr "Start _gjenoppretting"

#~ msgid "Minimize to tray on close"
#~ msgstr "Minimer til systemkurv ved lukking"

#~ msgid "Show notifications in tray area"
#~ msgstr "Vis merknader i systemkurvsfeltet"

#~ msgid "Show tray icon"
#~ msgstr "Vis systemkurvsikon"

#~ msgid "Start minimized"
#~ msgstr "Start minimert"

#~ msgid "Always show debug messages in the log"
#~ msgstr "Alltid vis feilrettingsmeldinger i loggen"

#~ msgid "Start fwbackups (minimized) when I login"
#~ msgstr "Start fwbackups (minimert) når jeg logger inn"

#~ msgid "Pycron installation directory:"
#~ msgstr "Installasjonsmappe for Pycron:"

#~ msgid "<b>Windows-specific options</b>"
#~ msgstr "<b>Windows-spesifikke valg</b>"

#~ msgid " "
#~ msgstr " "

#~ msgid ""
#~ "January\n"
#~ "February\n"
#~ "March\n"
#~ "April\n"
#~ "May\n"
#~ "June\n"
#~ "July\n"
#~ "August\n"
#~ "September\n"
#~ "October\n"
#~ "November\n"
#~ "December"
#~ msgstr ""
#~ "Januar\n"
#~ "Februar\n"
#~ "Mars\n"
#~ "April\n"
#~ "Mai\n"
#~ "Juni\n"
#~ "Juli\n"
#~ "August\n"
#~ "September\n"
#~ "Oktober\n"
#~ "November\n"
#~ "Desember"

#~ msgid ""
#~ "Sunday\n"
#~ "Monday\n"
#~ "Tuesday\n"
#~ "Wednesday\n"
#~ "Thurday\n"
#~ "Friday\n"
#~ "Saturday"
#~ msgstr ""
#~ "Søndag\n"
#~ "Mandag\n"
#~ "Tirsdag\n"
#~ "Onsdag\n"
#~ "Torsdag\n"
#~ "Fredag\n"
#~ "Lørdag"

#~ msgid ""
#~ "Sundays\n"
#~ "Mondays\n"
#~ "Tuesdays\n"
#~ "Wednesdays\n"
#~ "Thurdays\n"
#~ "Fridays\n"
#~ "Saturdays"
#~ msgstr ""
#~ "Søndager\n"
#~ "Mandager\n"
#~ "Tirsdager\n"
#~ "Onsdager\n"
#~ "Torsdager\n"
#~ "Fredager\n"
#~ "Lørdager"

#~ msgid ""
#~ "0 (12am)\n"
#~ "1 (1am)\n"
#~ "2 (2am)\n"
#~ "3 (3am)\n"
#~ "4 (4am)\n"
#~ "5 (5am)\n"
#~ "6 (6am)\n"
#~ "7 (7am)\n"
#~ "8 (8am)\n"
#~ "9 (9am)\n"
#~ "10 (10am)\n"
#~ "11 (11am)\n"
#~ "12 (Noon)\n"
#~ "13 (1pm)\n"
#~ "14 (2pm)\n"
#~ "15 (3pm)\n"
#~ "16 (4pm)\n"
#~ "17 (5pm)\n"
#~ "18 (6pm)\n"
#~ "19 (7pm)\n"
#~ "20 (8pm)\n"
#~ "21 (9pm)\n"
#~ "22 (10pm)\n"
#~ "23 (11pm)"
#~ msgstr ""
#~ "0 (12)\n"
#~ "1 (1)\n"
#~ "2 (2)\n"
#~ "3 (3)\n"
#~ "4 (4)\n"
#~ "5 (5)\n"
#~ "6 (6)\n"
#~ "7 (7)\n"
#~ "8 (8)\n"
#~ "9 (9)\n"
#~ "10 (10)\n"
#~ "11 (11)\n"
#~ "12 (12)\n"
#~ "13 (1)\n"
#~ "14 (2)\n"
#~ "15 (3)\n"
#~ "16 (4)\n"
#~ "17 (5)\n"
#~ "18 (6)\n"
#~ "19 (7)\n"
#~ "20 (8)\n"
#~ "21 (9)\n"
#~ "22 (10)\n"
#~ "23 (11)"
